export {default as Login } from "./login/login"
export {default as SignUp} from "./sigin/signin"
export {default as HomeVisitors} from "./homevisitors/homevisitors"
export {default as Home} from "./home/home"
export {default as UploadChannel} from "./Upload/upload"